%% % Пример 2
clear;
cla;
t=0:0.05:6*pi;
x=sin(t);
y=2*cos(t);
plot3(x, y ,t,'LineWidth', 2);
line([sin(7*pi/2),sin(7*pi/2)],[2*cos(7*pi/2)-1,2*cos(7*pi/2)+1],[7*pi/2,7*pi/2],'LineWidth', 2, 'Marker', '*');
line([sin(7*pi/2)-1,sin(7*pi/2)],[2*cos(7*pi/2),2*cos(7*pi/2)],[7*pi/2,7*pi/2],'LineWidth', 2, 'Marker', '*');
line([sin(7*pi/2),sin(7*pi/2)],[2*cos(7*pi/2),2*cos(7*pi/2)],[7*pi/2,7*pi/2],'LineWidth', 4, 'Marker', 'o', "Color",[1 0 0]);
grid on;
xlabel('X');
ylabel('Y');
zlabel('Z');
title('Пространственная спираль');
%% % Задания 1
clear;
cla;
a = input("Введите переменную a в уравнении ax+by+cz+d=0: ");
b = input("Введите переменную b в уравнении ax+by+cz+d=0: ");
c = input("Введите переменную c в уравнении ax+by+cz+d=0: ");
d = input("Введите переменную d в уравнении ax+by+cz+d=0: ");
points= -10:0.5:10;
[X, Y] = meshgrid(points, points); 


Z = -a/c.*X-b/c*Y-d/c;
surfc(X, Y, Z);
view(-38, 18);
title('ax+by+cz+d=0');
xlabel('x');
ylabel('y');
zlabel('z');
%% % Задание 2a
clear;
cla;
points= -10:0.2:10;
a = input("Введите переменную a в уравнении z=a*sin(sqrt(x^2+y^2))/sqrt(x^2+y^2): ");
[X, Y] = meshgrid(points, points); 
Z = (a.*sin(sqrt(X.^2+Y.^2)))./sqrt(X.^2+Y.^2);
subplot(2,1,2);
plot3(X,Y,Z);
title('z=a*sin(sqrt(x^2+y^2))/sqrt(x^2+y^2)');
xlabel('x');
ylabel('y');
zlabel('z');
subplot(2,1,1);
mesh(X,Y,Z);
title('z=a*sin(sqrt(x^2+y^2))/sqrt(x^2+y^2)');
xlabel('x');
ylabel('y');
zlabel('z');
%% % Задание 2b
clear;
cla;
points= -10:0.2:10;
[X, Y] = meshgrid(points, points); 
Z = -X.*sin(X)-Y.*cos(Y);
subplot(2,1,2);
plot3(X,Y,Z);
title('z=-x*sin(x)-y*cos(y)');
xlabel('x');
ylabel('y');
zlabel('z');
subplot(2,1,1);
mesh(X,Y,Z);
title('z=-x*sin(x)-y*cos(y)');
xlabel('x');
ylabel('y');
zlabel('z');
%% % Задание 3a
clear;
cla;
a = input("Введите переменную a в уравнении z=a*x*e^(-x^2-y^2): ");
points= -5:0.2:5;
[X, Y] = meshgrid(points, points); 
Z = a.*X.*exp(-X.^2-Y.^2);
subplot(3,1,1);
surf(X,Y,Z);
title('z=-x*sin(x)-y*cos(y)');
xlabel('x');
ylabel('y');
zlabel('z');
subplot(3,1,2);
surfc(X,Y,Z);
title('z=-x*sin(x)-y*cos(y)');
xlabel('x');
ylabel('y');
subplot(3,1,3);
mesh(X,Y,Z);
title('z=-x*sin(x)-y*cos(y)');
xlabel('x');
ylabel('y');
zlabel('z');
zlabel('z');
%% % Задание 3b
clear;
cla;
a = input("Введите переменную a в уравнении x=a*ch(α)cos(β); y=a*ch(α)sin(β); z=sh(α): ");
u= -5:0.2:5;
v = 0:0.2:2*pi;
[u, v] = meshgrid(u, v); 
X = a*cosh(u).*cos(v);
Y = a*cosh(u).*sin(v);
Z = sinh(u);
subplot(3,1,1);
surf(X,Y,Z);
title('Однополостный гиперболоид вращения');
xlabel('x');
ylabel('y');
zlabel('z');
subplot(3,1,2);
surfc(X,Y,Z);
title('Однополостный гиперболоид вращения');
xlabel('x');
ylabel('y');
subplot(3,1,3);
mesh(X,Y,Z);
title('Однополостный гиперболоид вращения');
xlabel('x');
ylabel('y');
zlabel('z');
zlabel('z');
%% % Задание 3d
clear;
cla;
a = input("Введите переменную a в уравнении x=a*ch(α)cos(β); y=a*sh(α)sin(β); z=c*ch(α): ");
c = input("Введите переменную a в уравнении x=a*ch(α)cos(β); y=a*sh(α)sin(β); z=c*ch(α): ");
u= 0:0.2:5;
v = 0:0.2:2*pi;
[u, v] = meshgrid(u, v); 
X = a*sinh(u).*cos(v);
Y = a*sinh(u).*sin(v);
Z = c*cosh(u);
subplot(3,1,1);
surf(X,Y,Z);
hold on;
surf(X,Y,-Z);
hold off;
title('Двуполостный гиперболоид вращения');
xlabel('x');
ylabel('y');
zlabel('z');
subplot(3,1,2);
surfc(X,Y,Z);
hold on;
surfc(X,Y,-Z);
hold off;
title('Двуполостный гиперболоид вращения');
xlabel('x');
ylabel('y');
subplot(3,1,3);
mesh(X,Y,Z);
hold on;
mesh(X,Y,-Z);
hold off;
title('Двуполостный гиперболоид вращения');
xlabel('x');
ylabel('y');
zlabel('z');
zlabel('z');